"""Data models for regulatory_testgen.

Clause and RegulationTable live in data_models/ (see pipeline.py). This
module defines the models specific to test-case generation.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class ClauseRole(BaseModel):
    """LLM-assigned classification of a single regulatory clause."""

    clause_id: str
    role: Literal[
        "performance_requirement",  # specifies measurable limits → generates test cases
        "test_procedure",           # describes how to execute a test → generates test cases
        "definition",               # defines a term → context only
        "administrative",           # approval, reporting, document management → skip
        "scope",                    # applicability of the regulation → skip
        "other",                    # catch-all for uncategorised clauses
    ]
    has_performance_table: bool = False
    reasoning: str = ""


class TestCase(BaseModel):
    """A single generated test case.

    Fields
    ------
    scenario        Narrative overview (multi-paragraph, human-readable).
    preconditions   Bullet-list of setup requirements before the test starts.
    test_steps      Numbered execution steps — what the tester does during the test.
    expected_behavior  Observable pass criteria / post-conditions.
    parameters      Key numeric values extracted from the clause or table row.
    source_clause_ids  Regulation clauses that this test case was derived from.
    reasoning_trace Agent's chain-of-thought (kept for thesis analysis, not shown to engineers).
    markdown        Full test case formatted as Markdown (generated by export.py).
    """

    test_id: str
    title: str
    scenario: str
    preconditions: list[str] = Field(default_factory=list)
    test_steps: list[str] = Field(default_factory=list)
    expected_behavior: list[str] = Field(default_factory=list)
    source_clause_ids: list[str] = Field(default_factory=list)
    parameters: dict[str, str] = Field(default_factory=dict)
    reasoning_trace: str = ""
    markdown: str = ""
